version: "3"

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
